### ISSUE TITLE
Possible to use your files on 2018 version of the Aero15W with i7-8750H?

### ISSUE THREAD

**Issue by Wonderboy1905** [Errrneist/Hackintosh-Aero-15W#5]
Hi Errneist,

do you think i will be able to use your files, as is, on the 2018 Gigabyte Aero 15 W v8 or will i have to change much?
From my understanding, there should not be much of a difference hardware wise, except for the processor...

Thanks

**Comment by wu-hongjun** [comment]
No. You can try, but I don't think it will work. (I am studying abroad so it took me a bit time to reply, sorry)

Before everything, I shall say that I do not have an Aero 15 v8 and nor do I have any mobile intel 8th gen platforms. But here are some things that I think you need to change to possibly make it partially work.

First, DSDT will not work. DSDT is from my laptop, and I suggest people even with the same v7 laptops to configure for themselves, and therefore for a v8 machine, it will definitely not work.

Secondly, you might need to change the GPU injection. I am still using the inject intel method, but you need to change that to work with your UHD630 iGPU.

Thirdly, you might want to check if your battery still matches with that using the v7 configuration. (It's in DSDT)

Fourth, Since the screen is 144hz, I am not sure what effect that will have on a hackintosh machine.

There are more to debate on, but since I do not have a v8 machine, there isn't much I can do. Do check other people's success on 8th H series platforms though, since you might be able to get around (At least some) with that.

**Comment by Wonderboy1905** [comment]
Wow, thank you very much for taking the time to answer my question so thoughtfully. I really appreciate it. I still have not decided on a laptop yet, but will consider one where all the quirks have been sorted out. I am kinda scared to break something on my own :D thanks again for your help

**Comment by wu-hongjun** [comment]
No problem. I've been looking for my next laptop too but I am thinking to wait for the 9th gen mobile chips and RTX cards for Windows works. (macOS is for coding anyways, so dGPU really doesn't matter). But if you are looking for one right now I would say also look into a Dell XPS 15 or Thinkpad X1 Extreme if you have a budget...that is a sleek laptop too.
